### ISSUE TITLE
Problem trying to set gui on data property

### ISSUE THREAD

**Issue by cettox** [zingchart/ZingChart-React#1]
It seems trying to limit some context menu elements by setting behaviours array of gui wont work.

**Comment by mike-schultz** [comment]
Hi there, could you send us over your JSON configuration? This could be a ZingChart library issue rather than an issue with the React component. I can't seem to replicate your issue using the React Component

**Comment by cettox** [comment]
Below you can see the "gui" part of the JSON configuration:
```
let getMyConfig = () => {
  return {
    "gui": {
      "behaviours": [
        {
          "id": "FullScreen",
          "enabled": "none"
        },
        {
          "id": "DownloadPDF",
          "enabled": "none"
        },
        {
          "id": "DownloadSVG",
          "enabled": "none"
        }
      ]
    },
    "graphset": [ Object.assign( {}, myConfigJSON ) ]
  };
};
```

**Comment by mike-schultz** [comment]
The attribute to modify the context menu is actually spelled differently using the alternate `behaviors` rather than `behaviours`

**Comment by cettox** [comment]
Cool, that is my bad. Thanks for pointing that out!
