### ISSUE TITLE
Missing Tooltips

### ISSUE THREAD

**Issue by nathan-wells** [zingchart/ZingChart-React#13]
On a mixed scatter and area chart, I am unable to view the tooltips for the scatter plot points when the number of points on the scatter plot exceeds 400 or so. The area chart's tooltips are still visible. On a pure scatter plot, I do not see this issue.

zingchart-react version 1.0.6, zingchart Version 2.7.2, Chrome on Windows 7

**Comment by damntrecky** [comment]
Please refer to the following documentation: https://www.zingchart.com/docs/api/json-configuration/graphset/plot/. The attribute `max-trackers` has a default of 800. The library stops adding event listeners for large charts and when you zoom in to view less than 800 nodes it will show the tooltips. You can adjust this value manually. It is weird you are seeing this behavior with less nodes, but adjusting this attribute may solve your issue. Please email into support@zingchart.com for a more in depth response.

**Comment by nathan-wells** [comment]
Thanks for the quick response! I will give that a shot. I'm surprised to hear that the default is 800 because on the pure scatter plot I'm still able to view the tooltips with 59663 data points.

**Comment by nathan-wells** [comment]
That works (within reason). I managed to crash chrome trying to test the limits, but I think that'll work as a solution for me. Thank you!
