### ISSUE TITLE
 TypeError: zingchart.render is not a function

### ISSUE THREAD

**Issue by trose89** [zingchart/ZingChart-React#2]
I upgraded to zingchart@2.2.0 and ran into this issue.

Looks like the zingchart code was changed to just set a `zingchart` variable on the global scope

Changing the first line of zingchart-react.js from

`var zingchart = require('zingchart');`

to

`require('zingchart');`

fixed the issue for me.

**Comment by mike-schultz** [comment]
Hi, 
The `zingchart` variable along with `ZC` have always been attached to the global scope and is no different in v2.2.0. However the way ZingChart is distributed did change. 

Previously, `zingchart.min.js` included this small snippet of code at the very bottom of the compiled code : 
```
if (typeof module !== 'undefined'){zingchart.MODULESDIR = "https://cdn.zingchart.com/modules/"; module.exports = zingchart};
```
This allowed for the zingchart global variable to be set inside of module.exports and to be consumed with the requirejs syntax.

With v2.2.0, we decided to drop this snippet of code at the bottom to not have a bias towards a specific package manager (npm in this case). Instead, the new package.json inside the repo (https://github.com/zingchart/ZingChart) points to a script called `index.js` which essentially does the same thing previously before. This method still allows users to require ZingChart as normal using requirejs syntax. 

In your development, are you by chance linking `zingchart` directly to the `zingchart.min.js` file? The package.json should be routing you to `index.js` as the main file instead now.

**Comment by trose89** [comment]
Oooooh yup, that's my problem. I had the package.json still pointed at zingchart.min.js after the upgrade. Thanks for the detailed response Mike.
