### ISSUE TITLE
Support react 17

### ISSUE THREAD

**Issue by bwillem** [zingchart/zingchart-react#30]
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from zingchart-react@3.1.0
```

**Comment by Misil4** [comment]
you can put --legacy-peer-deps when doing npm install
![image](https://user-images.githubusercontent.com/67839505/145408927-46719a75-4a56-438a-bd84-b706ef470e7a.png)

**Comment by jeanettephung** [comment]
Support added.
