### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by dev-sareno** [zingchart/zingchart-react#39]
The documentation on the [official website](https://www.zingchart.com/docs/integrations/react) is outdated.

It says
`import 'zingchart-react/dist/modules-es6/zingchart-depth.min.js';`
but the correct import is
`import 'zingchart/modules-es6/zingchart-depth.min.js';`

GitHub documentation is correct and updated but the one on the website.
Outdated documentation can be frustrating sometimes.

**Comment by jeanettephung** [comment]
Thank you for reporting this. We are updating the docs.
